# Generated by Django 4.1 on 2023-07-25 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboursAllocated',
            fields=[
                ('allocation_id', models.AutoField(primary_key=True, serialize=False)),
                ('labour_email', models.EmailField(max_length=254)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_services.booking')),
            ],
        ),
    ]
