# Generated by Django 4.1 on 2023-04-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.IntegerField(primary_key=True, serialize=False)),
                ('contractor_name', models.CharField(max_length=500)),
                ('contractor_email', models.EmailField(max_length=254)),
                ('labour_count', models.IntegerField()),
                ('date_of_booking', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Labour',
            fields=[
                ('skill', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('cost_per_hour', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('booking_id', models.IntegerField()),
                ('payment_date', models.DateField()),
                ('amount', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
