# Generated by Django 4.1 on 2023-12-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='contractor_email',
            field=models.EmailField(max_length=254),
        ),
    ]
