# Generated by Django 4.1 on 2023-08-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0002_booking_labour_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labour',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100),
        ),
    ]
