# Generated by Django 4.1 on 2024-01-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0003_alter_booking_contractor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date_and_time',
            field=models.DateTimeField(),
        ),
    ]
