# Generated by Django 4.1 on 2024-02-13 13:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0004_alter_notification_date_and_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='country',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='merchant_id',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 13, 19, 26, 22, 915036)),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(default='-1', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_services.booking'),
        ),
    ]
